//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:\My\MyProjects\Zsharp\src2\Maja\Maja.Compiler\MajaParser.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Maja.Compiler.Parser {
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="MajaParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public interface IMajaParserVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="MajaParser.compilation_unit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCompilation_unit([NotNull] MajaParser.Compilation_unitContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MajaParser.pub1_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPub1_decl([NotNull] MajaParser.Pub1_declContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MajaParser.pub2_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPub2_decl([NotNull] MajaParser.Pub2_declContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MajaParser.use_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUse_decl([NotNull] MajaParser.Use_declContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MajaParser.code_block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCode_block([NotNull] MajaParser.Code_blockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MajaParser.members_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMembers_decl([NotNull] MajaParser.Members_declContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MajaParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement([NotNull] MajaParser.StatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MajaParser.statement_flow"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement_flow([NotNull] MajaParser.Statement_flowContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MajaParser.statement_ret"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement_ret([NotNull] MajaParser.Statement_retContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MajaParser.function_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunction_decl([NotNull] MajaParser.Function_declContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MajaParser.function_decl_local"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunction_decl_local([NotNull] MajaParser.Function_decl_localContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MajaParser.parameter_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParameter_list([NotNull] MajaParser.Parameter_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MajaParser.parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParameter([NotNull] MajaParser.ParameterContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MajaParser.parameter_self"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParameter_self([NotNull] MajaParser.Parameter_selfContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MajaParser.type_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType_decl([NotNull] MajaParser.Type_declContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MajaParser.type_decl_members"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType_decl_members([NotNull] MajaParser.Type_decl_membersContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MajaParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType([NotNull] MajaParser.TypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MajaParser.type_parameter_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType_parameter_list([NotNull] MajaParser.Type_parameter_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MajaParser.type_parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType_parameter([NotNull] MajaParser.Type_parameterContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MajaParser.generic_parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGeneric_parameter([NotNull] MajaParser.Generic_parameterContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MajaParser.template_parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTemplate_parameter([NotNull] MajaParser.Template_parameterContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MajaParser.value_parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitValue_parameter([NotNull] MajaParser.Value_parameterContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MajaParser.type_argument_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType_argument_list([NotNull] MajaParser.Type_argument_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MajaParser.type_argument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType_argument([NotNull] MajaParser.Type_argumentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MajaParser.member_enum"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMember_enum([NotNull] MajaParser.Member_enumContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MajaParser.member_field"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMember_field([NotNull] MajaParser.Member_fieldContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MajaParser.member_rule"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMember_rule([NotNull] MajaParser.Member_ruleContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MajaParser.variable_decl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariable_decl([NotNull] MajaParser.Variable_declContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MajaParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression([NotNull] MajaParser.ExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MajaParser.expression_const"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression_const([NotNull] MajaParser.Expression_constContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MajaParser.expression_rule"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression_rule([NotNull] MajaParser.Expression_ruleContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MajaParser.name_qualified"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitName_qualified([NotNull] MajaParser.Name_qualifiedContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MajaParser.name_qualified_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitName_qualified_list([NotNull] MajaParser.Name_qualified_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MajaParser.name_identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitName_identifier([NotNull] MajaParser.Name_identifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MajaParser.name_identifier_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitName_identifier_list([NotNull] MajaParser.Name_identifier_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MajaParser.indent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIndent([NotNull] MajaParser.IndentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MajaParser.dedent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDedent([NotNull] MajaParser.DedentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MajaParser.newline"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNewline([NotNull] MajaParser.NewlineContext context);
}
} // namespace Maja.Compiler.Parser
