//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:\My\MyProjects\Zsharp\src2\Maja\Maja.Compiler\MajaParser.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Maja.Compiler.Parser {
using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public partial class MajaParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		INDENT=1, DEDENT=2, COMMENTstart=3, COMMENTwarning=4, COMMENT=5, RET=6, 
		PUB=7, USE=8, SELF=9, IDENTIFIER=10, PARENopen=11, PARENclose=12, ANGLEopen=13, 
		ANGLEclose=14, HASH=15, COLON=16, DOT=17, EQ=18, DISCARD=19, COMMA=20, 
		SP=21, EOL=22;
	public const int
		RULE_compilation_unit = 0, RULE_pub1_decl = 1, RULE_pub2_decl = 2, RULE_use_decl = 3, 
		RULE_code_block = 4, RULE_members_decl = 5, RULE_statement = 6, RULE_statement_flow = 7, 
		RULE_statement_ret = 8, RULE_function_decl = 9, RULE_function_decl_local = 10, 
		RULE_parameter_list = 11, RULE_parameter = 12, RULE_parameter_self = 13, 
		RULE_type_decl = 14, RULE_type_decl_members = 15, RULE_type = 16, RULE_type_parameter_list = 17, 
		RULE_type_parameter = 18, RULE_generic_parameter = 19, RULE_template_parameter = 20, 
		RULE_value_parameter = 21, RULE_type_argument_list = 22, RULE_type_argument = 23, 
		RULE_member_enum = 24, RULE_member_field = 25, RULE_member_rule = 26, 
		RULE_variable_decl = 27, RULE_expression = 28, RULE_expression_const = 29, 
		RULE_expression_rule = 30, RULE_name_qualified = 31, RULE_name_qualified_list = 32, 
		RULE_name_identifier = 33, RULE_name_identifier_list = 34, RULE_indent = 35, 
		RULE_dedent = 36, RULE_newline = 37;
	public static readonly string[] ruleNames = {
		"compilation_unit", "pub1_decl", "pub2_decl", "use_decl", "code_block", 
		"members_decl", "statement", "statement_flow", "statement_ret", "function_decl", 
		"function_decl_local", "parameter_list", "parameter", "parameter_self", 
		"type_decl", "type_decl_members", "type", "type_parameter_list", "type_parameter", 
		"generic_parameter", "template_parameter", "value_parameter", "type_argument_list", 
		"type_argument", "member_enum", "member_field", "member_rule", "variable_decl", 
		"expression", "expression_const", "expression_rule", "name_qualified", 
		"name_qualified_list", "name_identifier", "name_identifier_list", "indent", 
		"dedent", "newline"
	};

	private static readonly string[] _LiteralNames = {
		null, null, null, "'#_'", "'##'", null, "'ret'", "'pub'", "'use'", "'self'", 
		null, "'('", "')'", "'<'", "'>'", "'#'", "':'", "'.'", "'='", "'_'", "','", 
		"' '"
	};
	private static readonly string[] _SymbolicNames = {
		null, "INDENT", "DEDENT", "COMMENTstart", "COMMENTwarning", "COMMENT", 
		"RET", "PUB", "USE", "SELF", "IDENTIFIER", "PARENopen", "PARENclose", 
		"ANGLEopen", "ANGLEclose", "HASH", "COLON", "DOT", "EQ", "DISCARD", "COMMA", 
		"SP", "EOL"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "MajaParser.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static MajaParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public MajaParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public MajaParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class Compilation_unitContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Use_declContext[] use_decl() {
			return GetRuleContexts<Use_declContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Use_declContext use_decl(int i) {
			return GetRuleContext<Use_declContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Pub1_declContext[] pub1_decl() {
			return GetRuleContexts<Pub1_declContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Pub1_declContext pub1_decl(int i) {
			return GetRuleContext<Pub1_declContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Pub2_declContext[] pub2_decl() {
			return GetRuleContexts<Pub2_declContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Pub2_declContext pub2_decl(int i) {
			return GetRuleContext<Pub2_declContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public NewlineContext[] newline() {
			return GetRuleContexts<NewlineContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public NewlineContext newline(int i) {
			return GetRuleContext<NewlineContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Members_declContext[] members_decl() {
			return GetRuleContexts<Members_declContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Members_declContext members_decl(int i) {
			return GetRuleContext<Members_declContext>(i);
		}
		public Compilation_unitContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_compilation_unit; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMajaParserVisitor<TResult> typedVisitor = visitor as IMajaParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitCompilation_unit(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Compilation_unitContext compilation_unit() {
		Compilation_unitContext _localctx = new Compilation_unitContext(Context, State);
		EnterRule(_localctx, 0, RULE_compilation_unit);
		int _la;
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 82;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,1,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					{
					State = 80;
					ErrorHandler.Sync(this);
					switch ( Interpreter.AdaptivePredict(TokenStream,0,Context) ) {
					case 1:
						{
						State = 76;
						use_decl();
						}
						break;
					case 2:
						{
						State = 77;
						pub1_decl();
						}
						break;
					case 3:
						{
						State = 78;
						pub2_decl();
						}
						break;
					case 4:
						{
						State = 79;
						newline();
						}
						break;
					}
					} 
				}
				State = 84;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,1,Context);
			}
			State = 89;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << COMMENT) | (1L << IDENTIFIER) | (1L << SP) | (1L << EOL))) != 0)) {
				{
				State = 87;
				ErrorHandler.Sync(this);
				switch (TokenStream.LA(1)) {
				case IDENTIFIER:
					{
					State = 85;
					members_decl();
					}
					break;
				case COMMENT:
				case SP:
				case EOL:
					{
					State = 86;
					newline();
					}
					break;
				default:
					throw new NoViableAltException(this);
				}
				}
				State = 91;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Pub1_declContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode PUB() { return GetToken(MajaParser.PUB, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Name_qualified_listContext name_qualified_list() {
			return GetRuleContext<Name_qualified_listContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public NewlineContext newline() {
			return GetRuleContext<NewlineContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] SP() { return GetTokens(MajaParser.SP); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SP(int i) {
			return GetToken(MajaParser.SP, i);
		}
		public Pub1_declContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_pub1_decl; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMajaParserVisitor<TResult> typedVisitor = visitor as IMajaParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPub1_decl(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Pub1_declContext pub1_decl() {
		Pub1_declContext _localctx = new Pub1_declContext(Context, State);
		EnterRule(_localctx, 2, RULE_pub1_decl);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 92;
			Match(PUB);
			State = 94;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			do {
				{
				{
				State = 93;
				Match(SP);
				}
				}
				State = 96;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			} while ( _la==SP );
			State = 98;
			name_qualified_list();
			State = 99;
			newline();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Pub2_declContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode PUB() { return GetToken(MajaParser.PUB, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public NewlineContext[] newline() {
			return GetRuleContexts<NewlineContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public NewlineContext newline(int i) {
			return GetRuleContext<NewlineContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public IndentContext indent() {
			return GetRuleContext<IndentContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Name_qualified_listContext name_qualified_list() {
			return GetRuleContext<Name_qualified_listContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public DedentContext dedent() {
			return GetRuleContext<DedentContext>(0);
		}
		public Pub2_declContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_pub2_decl; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMajaParserVisitor<TResult> typedVisitor = visitor as IMajaParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPub2_decl(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Pub2_declContext pub2_decl() {
		Pub2_declContext _localctx = new Pub2_declContext(Context, State);
		EnterRule(_localctx, 4, RULE_pub2_decl);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 101;
			Match(PUB);
			State = 102;
			newline();
			State = 103;
			indent();
			State = 104;
			name_qualified_list();
			State = 105;
			newline();
			State = 106;
			dedent();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Use_declContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode USE() { return GetToken(MajaParser.USE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Name_qualifiedContext name_qualified() {
			return GetRuleContext<Name_qualifiedContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public NewlineContext newline() {
			return GetRuleContext<NewlineContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] SP() { return GetTokens(MajaParser.SP); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SP(int i) {
			return GetToken(MajaParser.SP, i);
		}
		public Use_declContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_use_decl; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMajaParserVisitor<TResult> typedVisitor = visitor as IMajaParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitUse_decl(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Use_declContext use_decl() {
		Use_declContext _localctx = new Use_declContext(Context, State);
		EnterRule(_localctx, 6, RULE_use_decl);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 108;
			Match(USE);
			State = 110;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			do {
				{
				{
				State = 109;
				Match(SP);
				}
				}
				State = 112;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			} while ( _la==SP );
			State = 114;
			name_qualified();
			State = 115;
			newline();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Code_blockContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public StatementContext[] statement() {
			return GetRuleContexts<StatementContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public StatementContext statement(int i) {
			return GetRuleContext<StatementContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Members_declContext[] members_decl() {
			return GetRuleContexts<Members_declContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Members_declContext members_decl(int i) {
			return GetRuleContext<Members_declContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public NewlineContext[] newline() {
			return GetRuleContexts<NewlineContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public NewlineContext newline(int i) {
			return GetRuleContext<NewlineContext>(i);
		}
		public Code_blockContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_code_block; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMajaParserVisitor<TResult> typedVisitor = visitor as IMajaParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitCode_block(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Code_blockContext code_block() {
		Code_blockContext _localctx = new Code_blockContext(Context, State);
		EnterRule(_localctx, 8, RULE_code_block);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 120;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			do {
				{
				State = 120;
				ErrorHandler.Sync(this);
				switch (TokenStream.LA(1)) {
				case RET:
					{
					State = 117;
					statement();
					}
					break;
				case IDENTIFIER:
					{
					State = 118;
					members_decl();
					}
					break;
				case COMMENT:
				case SP:
				case EOL:
					{
					State = 119;
					newline();
					}
					break;
				default:
					throw new NoViableAltException(this);
				}
				}
				State = 122;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			} while ( (((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << COMMENT) | (1L << RET) | (1L << IDENTIFIER) | (1L << SP) | (1L << EOL))) != 0) );
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Members_declContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Function_declContext function_decl() {
			return GetRuleContext<Function_declContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Type_declContext type_decl() {
			return GetRuleContext<Type_declContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Variable_declContext variable_decl() {
			return GetRuleContext<Variable_declContext>(0);
		}
		public Members_declContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_members_decl; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMajaParserVisitor<TResult> typedVisitor = visitor as IMajaParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitMembers_decl(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Members_declContext members_decl() {
		Members_declContext _localctx = new Members_declContext(Context, State);
		EnterRule(_localctx, 10, RULE_members_decl);
		try {
			State = 127;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,8,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 124;
				function_decl();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 125;
				type_decl();
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 126;
				variable_decl();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class StatementContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Statement_flowContext statement_flow() {
			return GetRuleContext<Statement_flowContext>(0);
		}
		public StatementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_statement; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMajaParserVisitor<TResult> typedVisitor = visitor as IMajaParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitStatement(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public StatementContext statement() {
		StatementContext _localctx = new StatementContext(Context, State);
		EnterRule(_localctx, 12, RULE_statement);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 129;
			statement_flow();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Statement_flowContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Statement_retContext statement_ret() {
			return GetRuleContext<Statement_retContext>(0);
		}
		public Statement_flowContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_statement_flow; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMajaParserVisitor<TResult> typedVisitor = visitor as IMajaParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitStatement_flow(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Statement_flowContext statement_flow() {
		Statement_flowContext _localctx = new Statement_flowContext(Context, State);
		EnterRule(_localctx, 14, RULE_statement_flow);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 131;
			statement_ret();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Statement_retContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RET() { return GetToken(MajaParser.RET, 0); }
		public Statement_retContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_statement_ret; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMajaParserVisitor<TResult> typedVisitor = visitor as IMajaParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitStatement_ret(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Statement_retContext statement_ret() {
		Statement_retContext _localctx = new Statement_retContext(Context, State);
		EnterRule(_localctx, 16, RULE_statement_ret);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 133;
			Match(RET);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Function_declContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Name_identifierContext name_identifier() {
			return GetRuleContext<Name_identifierContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COLON() { return GetToken(MajaParser.COLON, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SP() { return GetToken(MajaParser.SP, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Parameter_listContext parameter_list() {
			return GetRuleContext<Parameter_listContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public NewlineContext newline() {
			return GetRuleContext<NewlineContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public IndentContext indent() {
			return GetRuleContext<IndentContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Code_blockContext code_block() {
			return GetRuleContext<Code_blockContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public DedentContext dedent() {
			return GetRuleContext<DedentContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Type_parameter_listContext type_parameter_list() {
			return GetRuleContext<Type_parameter_listContext>(0);
		}
		public Function_declContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_function_decl; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMajaParserVisitor<TResult> typedVisitor = visitor as IMajaParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunction_decl(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Function_declContext function_decl() {
		Function_declContext _localctx = new Function_declContext(Context, State);
		EnterRule(_localctx, 18, RULE_function_decl);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 135;
			name_identifier();
			State = 136;
			Match(COLON);
			State = 137;
			Match(SP);
			State = 139;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==ANGLEopen) {
				{
				State = 138;
				type_parameter_list();
				}
			}

			State = 141;
			parameter_list();
			State = 142;
			newline();
			State = 143;
			indent();
			State = 144;
			code_block();
			State = 145;
			dedent();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Function_decl_localContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public IndentContext indent() {
			return GetRuleContext<IndentContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Function_declContext function_decl() {
			return GetRuleContext<Function_declContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public DedentContext dedent() {
			return GetRuleContext<DedentContext>(0);
		}
		public Function_decl_localContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_function_decl_local; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMajaParserVisitor<TResult> typedVisitor = visitor as IMajaParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunction_decl_local(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Function_decl_localContext function_decl_local() {
		Function_decl_localContext _localctx = new Function_decl_localContext(Context, State);
		EnterRule(_localctx, 20, RULE_function_decl_local);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 147;
			indent();
			State = 148;
			function_decl();
			State = 149;
			dedent();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Parameter_listContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode PARENopen() { return GetToken(MajaParser.PARENopen, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode PARENclose() { return GetToken(MajaParser.PARENclose, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ParameterContext[] parameter() {
			return GetRuleContexts<ParameterContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ParameterContext parameter(int i) {
			return GetRuleContext<ParameterContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Parameter_selfContext parameter_self() {
			return GetRuleContext<Parameter_selfContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] COMMA() { return GetTokens(MajaParser.COMMA); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COMMA(int i) {
			return GetToken(MajaParser.COMMA, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] SP() { return GetTokens(MajaParser.SP); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SP(int i) {
			return GetToken(MajaParser.SP, i);
		}
		public Parameter_listContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_parameter_list; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMajaParserVisitor<TResult> typedVisitor = visitor as IMajaParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitParameter_list(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Parameter_listContext parameter_list() {
		Parameter_listContext _localctx = new Parameter_listContext(Context, State);
		EnterRule(_localctx, 22, RULE_parameter_list);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 151;
			Match(PARENopen);
			State = 162;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case IDENTIFIER:
				{
				State = 152;
				parameter();
				}
				break;
			case SELF:
				{
				State = 153;
				parameter_self();
				State = 159;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while (_la==COMMA) {
					{
					{
					State = 154;
					Match(COMMA);
					State = 155;
					Match(SP);
					State = 156;
					parameter();
					}
					}
					State = 161;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				}
				break;
			case PARENclose:
				break;
			default:
				break;
			}
			State = 164;
			Match(PARENclose);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ParameterContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Name_identifierContext name_identifier() {
			return GetRuleContext<Name_identifierContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COLON() { return GetToken(MajaParser.COLON, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SP() { return GetToken(MajaParser.SP, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public TypeContext type() {
			return GetRuleContext<TypeContext>(0);
		}
		public ParameterContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_parameter; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMajaParserVisitor<TResult> typedVisitor = visitor as IMajaParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitParameter(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ParameterContext parameter() {
		ParameterContext _localctx = new ParameterContext(Context, State);
		EnterRule(_localctx, 24, RULE_parameter);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 166;
			name_identifier();
			State = 167;
			Match(COLON);
			State = 168;
			Match(SP);
			State = 169;
			type();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Parameter_selfContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SELF() { return GetToken(MajaParser.SELF, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COLON() { return GetToken(MajaParser.COLON, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SP() { return GetToken(MajaParser.SP, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public TypeContext type() {
			return GetRuleContext<TypeContext>(0);
		}
		public Parameter_selfContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_parameter_self; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMajaParserVisitor<TResult> typedVisitor = visitor as IMajaParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitParameter_self(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Parameter_selfContext parameter_self() {
		Parameter_selfContext _localctx = new Parameter_selfContext(Context, State);
		EnterRule(_localctx, 26, RULE_parameter_self);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 171;
			Match(SELF);
			State = 172;
			Match(COLON);
			State = 173;
			Match(SP);
			State = 174;
			type();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Type_declContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Name_identifierContext name_identifier() {
			return GetRuleContext<Name_identifierContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public NewlineContext newline() {
			return GetRuleContext<NewlineContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Type_parameter_listContext type_parameter_list() {
			return GetRuleContext<Type_parameter_listContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COLON() { return GetToken(MajaParser.COLON, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SP() { return GetToken(MajaParser.SP, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public TypeContext type() {
			return GetRuleContext<TypeContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DISCARD() { return GetToken(MajaParser.DISCARD, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public IndentContext indent() {
			return GetRuleContext<IndentContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Type_decl_membersContext type_decl_members() {
			return GetRuleContext<Type_decl_membersContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public DedentContext dedent() {
			return GetRuleContext<DedentContext>(0);
		}
		public Type_declContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_type_decl; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMajaParserVisitor<TResult> typedVisitor = visitor as IMajaParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitType_decl(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Type_declContext type_decl() {
		Type_declContext _localctx = new Type_declContext(Context, State);
		EnterRule(_localctx, 28, RULE_type_decl);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 176;
			name_identifier();
			State = 178;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==ANGLEopen) {
				{
				State = 177;
				type_parameter_list();
				}
			}

			State = 183;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==COLON) {
				{
				State = 180;
				Match(COLON);
				State = 181;
				Match(SP);
				State = 182;
				type();
				}
			}

			State = 186;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==DISCARD) {
				{
				State = 185;
				Match(DISCARD);
				}
			}

			State = 188;
			newline();
			State = 193;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==INDENT) {
				{
				State = 189;
				indent();
				State = 190;
				type_decl_members();
				State = 191;
				dedent();
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Type_decl_membersContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public NewlineContext[] newline() {
			return GetRuleContexts<NewlineContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public NewlineContext newline(int i) {
			return GetRuleContext<NewlineContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Member_enumContext[] member_enum() {
			return GetRuleContexts<Member_enumContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Member_enumContext member_enum(int i) {
			return GetRuleContext<Member_enumContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Member_fieldContext[] member_field() {
			return GetRuleContexts<Member_fieldContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Member_fieldContext member_field(int i) {
			return GetRuleContext<Member_fieldContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Member_ruleContext[] member_rule() {
			return GetRuleContexts<Member_ruleContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Member_ruleContext member_rule(int i) {
			return GetRuleContext<Member_ruleContext>(i);
		}
		public Type_decl_membersContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_type_decl_members; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMajaParserVisitor<TResult> typedVisitor = visitor as IMajaParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitType_decl_members(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Type_decl_membersContext type_decl_members() {
		Type_decl_membersContext _localctx = new Type_decl_membersContext(Context, State);
		EnterRule(_localctx, 30, RULE_type_decl_members);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 202;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			do {
				{
				{
				State = 198;
				ErrorHandler.Sync(this);
				switch ( Interpreter.AdaptivePredict(TokenStream,16,Context) ) {
				case 1:
					{
					State = 195;
					member_enum();
					}
					break;
				case 2:
					{
					State = 196;
					member_field();
					}
					break;
				case 3:
					{
					State = 197;
					member_rule();
					}
					break;
				}
				State = 200;
				newline();
				}
				}
				State = 204;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			} while ( _la==IDENTIFIER || _la==HASH );
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class TypeContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Name_identifierContext name_identifier() {
			return GetRuleContext<Name_identifierContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Type_argument_listContext type_argument_list() {
			return GetRuleContext<Type_argument_listContext>(0);
		}
		public TypeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_type; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMajaParserVisitor<TResult> typedVisitor = visitor as IMajaParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitType(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public TypeContext type() {
		TypeContext _localctx = new TypeContext(Context, State);
		EnterRule(_localctx, 32, RULE_type);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 206;
			name_identifier();
			State = 208;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==ANGLEopen) {
				{
				State = 207;
				type_argument_list();
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Type_parameter_listContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ANGLEopen() { return GetToken(MajaParser.ANGLEopen, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Type_parameterContext[] type_parameter() {
			return GetRuleContexts<Type_parameterContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Type_parameterContext type_parameter(int i) {
			return GetRuleContext<Type_parameterContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ANGLEclose() { return GetToken(MajaParser.ANGLEclose, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] COMMA() { return GetTokens(MajaParser.COMMA); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COMMA(int i) {
			return GetToken(MajaParser.COMMA, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] SP() { return GetTokens(MajaParser.SP); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SP(int i) {
			return GetToken(MajaParser.SP, i);
		}
		public Type_parameter_listContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_type_parameter_list; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMajaParserVisitor<TResult> typedVisitor = visitor as IMajaParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitType_parameter_list(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Type_parameter_listContext type_parameter_list() {
		Type_parameter_listContext _localctx = new Type_parameter_listContext(Context, State);
		EnterRule(_localctx, 34, RULE_type_parameter_list);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 210;
			Match(ANGLEopen);
			State = 211;
			type_parameter();
			State = 217;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==COMMA) {
				{
				{
				State = 212;
				Match(COMMA);
				State = 213;
				Match(SP);
				State = 214;
				type_parameter();
				}
				}
				State = 219;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 220;
			Match(ANGLEclose);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Type_parameterContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Generic_parameterContext generic_parameter() {
			return GetRuleContext<Generic_parameterContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Template_parameterContext template_parameter() {
			return GetRuleContext<Template_parameterContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Value_parameterContext value_parameter() {
			return GetRuleContext<Value_parameterContext>(0);
		}
		public Type_parameterContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_type_parameter; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMajaParserVisitor<TResult> typedVisitor = visitor as IMajaParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitType_parameter(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Type_parameterContext type_parameter() {
		Type_parameterContext _localctx = new Type_parameterContext(Context, State);
		EnterRule(_localctx, 36, RULE_type_parameter);
		try {
			State = 225;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case IDENTIFIER:
				EnterOuterAlt(_localctx, 1);
				{
				State = 222;
				generic_parameter();
				}
				break;
			case HASH:
				EnterOuterAlt(_localctx, 2);
				{
				State = 223;
				template_parameter();
				}
				break;
			case ANGLEclose:
			case COMMA:
				EnterOuterAlt(_localctx, 3);
				{
				State = 224;
				value_parameter();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Generic_parameterContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Name_identifierContext name_identifier() {
			return GetRuleContext<Name_identifierContext>(0);
		}
		public Generic_parameterContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_generic_parameter; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMajaParserVisitor<TResult> typedVisitor = visitor as IMajaParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitGeneric_parameter(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Generic_parameterContext generic_parameter() {
		Generic_parameterContext _localctx = new Generic_parameterContext(Context, State);
		EnterRule(_localctx, 38, RULE_generic_parameter);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 227;
			name_identifier();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Template_parameterContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode HASH() { return GetToken(MajaParser.HASH, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Name_identifierContext name_identifier() {
			return GetRuleContext<Name_identifierContext>(0);
		}
		public Template_parameterContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_template_parameter; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMajaParserVisitor<TResult> typedVisitor = visitor as IMajaParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitTemplate_parameter(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Template_parameterContext template_parameter() {
		Template_parameterContext _localctx = new Template_parameterContext(Context, State);
		EnterRule(_localctx, 40, RULE_template_parameter);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 229;
			Match(HASH);
			State = 230;
			name_identifier();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Value_parameterContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public Value_parameterContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_value_parameter; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMajaParserVisitor<TResult> typedVisitor = visitor as IMajaParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitValue_parameter(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Value_parameterContext value_parameter() {
		Value_parameterContext _localctx = new Value_parameterContext(Context, State);
		EnterRule(_localctx, 42, RULE_value_parameter);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 232;
			expression();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Type_argument_listContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ANGLEopen() { return GetToken(MajaParser.ANGLEopen, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Type_argumentContext[] type_argument() {
			return GetRuleContexts<Type_argumentContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Type_argumentContext type_argument(int i) {
			return GetRuleContext<Type_argumentContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ANGLEclose() { return GetToken(MajaParser.ANGLEclose, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] COMMA() { return GetTokens(MajaParser.COMMA); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COMMA(int i) {
			return GetToken(MajaParser.COMMA, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] SP() { return GetTokens(MajaParser.SP); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SP(int i) {
			return GetToken(MajaParser.SP, i);
		}
		public Type_argument_listContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_type_argument_list; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMajaParserVisitor<TResult> typedVisitor = visitor as IMajaParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitType_argument_list(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Type_argument_listContext type_argument_list() {
		Type_argument_listContext _localctx = new Type_argument_listContext(Context, State);
		EnterRule(_localctx, 44, RULE_type_argument_list);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 234;
			Match(ANGLEopen);
			State = 235;
			type_argument();
			State = 241;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==COMMA) {
				{
				{
				State = 236;
				Match(COMMA);
				State = 237;
				Match(SP);
				State = 238;
				type_argument();
				}
				}
				State = 243;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 244;
			Match(ANGLEclose);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Type_argumentContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Name_identifierContext name_identifier() {
			return GetRuleContext<Name_identifierContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public Type_argumentContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_type_argument; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMajaParserVisitor<TResult> typedVisitor = visitor as IMajaParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitType_argument(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Type_argumentContext type_argument() {
		Type_argumentContext _localctx = new Type_argumentContext(Context, State);
		EnterRule(_localctx, 46, RULE_type_argument);
		try {
			State = 248;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case IDENTIFIER:
				EnterOuterAlt(_localctx, 1);
				{
				State = 246;
				name_identifier();
				}
				break;
			case ANGLEclose:
			case COMMA:
				EnterOuterAlt(_localctx, 2);
				{
				State = 247;
				expression();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Member_enumContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Name_identifierContext name_identifier() {
			return GetRuleContext<Name_identifierContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] SP() { return GetTokens(MajaParser.SP); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SP(int i) {
			return GetToken(MajaParser.SP, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode EQ() { return GetToken(MajaParser.EQ, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Expression_constContext expression_const() {
			return GetRuleContext<Expression_constContext>(0);
		}
		public Member_enumContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_member_enum; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMajaParserVisitor<TResult> typedVisitor = visitor as IMajaParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitMember_enum(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Member_enumContext member_enum() {
		Member_enumContext _localctx = new Member_enumContext(Context, State);
		EnterRule(_localctx, 48, RULE_member_enum);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 250;
			name_identifier();
			State = 255;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,23,Context) ) {
			case 1:
				{
				State = 251;
				Match(SP);
				State = 252;
				Match(EQ);
				State = 253;
				Match(SP);
				State = 254;
				expression_const();
				}
				break;
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Member_fieldContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Name_identifierContext name_identifier() {
			return GetRuleContext<Name_identifierContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COLON() { return GetToken(MajaParser.COLON, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SP() { return GetToken(MajaParser.SP, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public TypeContext type() {
			return GetRuleContext<TypeContext>(0);
		}
		public Member_fieldContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_member_field; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMajaParserVisitor<TResult> typedVisitor = visitor as IMajaParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitMember_field(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Member_fieldContext member_field() {
		Member_fieldContext _localctx = new Member_fieldContext(Context, State);
		EnterRule(_localctx, 50, RULE_member_field);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 257;
			name_identifier();
			State = 258;
			Match(COLON);
			State = 259;
			Match(SP);
			State = 260;
			type();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Member_ruleContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode HASH() { return GetToken(MajaParser.HASH, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Name_identifierContext name_identifier() {
			return GetRuleContext<Name_identifierContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SP() { return GetToken(MajaParser.SP, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Expression_ruleContext expression_rule() {
			return GetRuleContext<Expression_ruleContext>(0);
		}
		public Member_ruleContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_member_rule; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMajaParserVisitor<TResult> typedVisitor = visitor as IMajaParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitMember_rule(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Member_ruleContext member_rule() {
		Member_ruleContext _localctx = new Member_ruleContext(Context, State);
		EnterRule(_localctx, 52, RULE_member_rule);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 262;
			Match(HASH);
			State = 263;
			name_identifier();
			State = 264;
			Match(SP);
			State = 265;
			expression_rule();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Variable_declContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Name_identifierContext name_identifier() {
			return GetRuleContext<Name_identifierContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COLON() { return GetToken(MajaParser.COLON, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] SP() { return GetTokens(MajaParser.SP); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SP(int i) {
			return GetToken(MajaParser.SP, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public TypeContext type() {
			return GetRuleContext<TypeContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode EQ() { return GetToken(MajaParser.EQ, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public Variable_declContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_variable_decl; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMajaParserVisitor<TResult> typedVisitor = visitor as IMajaParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitVariable_decl(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Variable_declContext variable_decl() {
		Variable_declContext _localctx = new Variable_declContext(Context, State);
		EnterRule(_localctx, 54, RULE_variable_decl);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 267;
			name_identifier();
			State = 269;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==SP) {
				{
				State = 268;
				Match(SP);
				}
			}

			State = 271;
			Match(COLON);
			State = 274;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,25,Context) ) {
			case 1:
				{
				State = 272;
				Match(SP);
				State = 273;
				type();
				}
				break;
			}
			State = 278;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==EQ) {
				{
				State = 276;
				Match(EQ);
				State = 277;
				expression();
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ExpressionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Expression_constContext expression_const() {
			return GetRuleContext<Expression_constContext>(0);
		}
		public ExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expression; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMajaParserVisitor<TResult> typedVisitor = visitor as IMajaParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitExpression(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ExpressionContext expression() {
		ExpressionContext _localctx = new ExpressionContext(Context, State);
		EnterRule(_localctx, 56, RULE_expression);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 280;
			expression_const();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Expression_constContext : ParserRuleContext {
		public Expression_constContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expression_const; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMajaParserVisitor<TResult> typedVisitor = visitor as IMajaParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitExpression_const(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Expression_constContext expression_const() {
		Expression_constContext _localctx = new Expression_constContext(Context, State);
		EnterRule(_localctx, 58, RULE_expression_const);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Expression_ruleContext : ParserRuleContext {
		public Expression_ruleContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expression_rule; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMajaParserVisitor<TResult> typedVisitor = visitor as IMajaParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitExpression_rule(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Expression_ruleContext expression_rule() {
		Expression_ruleContext _localctx = new Expression_ruleContext(Context, State);
		EnterRule(_localctx, 60, RULE_expression_rule);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Name_qualifiedContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Name_identifierContext[] name_identifier() {
			return GetRuleContexts<Name_identifierContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Name_identifierContext name_identifier(int i) {
			return GetRuleContext<Name_identifierContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] DOT() { return GetTokens(MajaParser.DOT); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DOT(int i) {
			return GetToken(MajaParser.DOT, i);
		}
		public Name_qualifiedContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_name_qualified; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMajaParserVisitor<TResult> typedVisitor = visitor as IMajaParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitName_qualified(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Name_qualifiedContext name_qualified() {
		Name_qualifiedContext _localctx = new Name_qualifiedContext(Context, State);
		EnterRule(_localctx, 62, RULE_name_qualified);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 286;
			name_identifier();
			State = 291;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==DOT) {
				{
				{
				State = 287;
				Match(DOT);
				State = 288;
				name_identifier();
				}
				}
				State = 293;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Name_qualified_listContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Name_qualifiedContext[] name_qualified() {
			return GetRuleContexts<Name_qualifiedContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Name_qualifiedContext name_qualified(int i) {
			return GetRuleContext<Name_qualifiedContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] COMMA() { return GetTokens(MajaParser.COMMA); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COMMA(int i) {
			return GetToken(MajaParser.COMMA, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] SP() { return GetTokens(MajaParser.SP); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SP(int i) {
			return GetToken(MajaParser.SP, i);
		}
		public Name_qualified_listContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_name_qualified_list; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMajaParserVisitor<TResult> typedVisitor = visitor as IMajaParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitName_qualified_list(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Name_qualified_listContext name_qualified_list() {
		Name_qualified_listContext _localctx = new Name_qualified_listContext(Context, State);
		EnterRule(_localctx, 64, RULE_name_qualified_list);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 294;
			name_qualified();
			State = 304;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==COMMA) {
				{
				{
				State = 295;
				Match(COMMA);
				State = 297;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				do {
					{
					{
					State = 296;
					Match(SP);
					}
					}
					State = 299;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				} while ( _la==SP );
				State = 301;
				name_qualified();
				}
				}
				State = 306;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Name_identifierContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IDENTIFIER() { return GetToken(MajaParser.IDENTIFIER, 0); }
		public Name_identifierContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_name_identifier; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMajaParserVisitor<TResult> typedVisitor = visitor as IMajaParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitName_identifier(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Name_identifierContext name_identifier() {
		Name_identifierContext _localctx = new Name_identifierContext(Context, State);
		EnterRule(_localctx, 66, RULE_name_identifier);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 307;
			Match(IDENTIFIER);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Name_identifier_listContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Name_identifierContext[] name_identifier() {
			return GetRuleContexts<Name_identifierContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Name_identifierContext name_identifier(int i) {
			return GetRuleContext<Name_identifierContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] COMMA() { return GetTokens(MajaParser.COMMA); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COMMA(int i) {
			return GetToken(MajaParser.COMMA, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] SP() { return GetTokens(MajaParser.SP); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SP(int i) {
			return GetToken(MajaParser.SP, i);
		}
		public Name_identifier_listContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_name_identifier_list; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMajaParserVisitor<TResult> typedVisitor = visitor as IMajaParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitName_identifier_list(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Name_identifier_listContext name_identifier_list() {
		Name_identifier_listContext _localctx = new Name_identifier_listContext(Context, State);
		EnterRule(_localctx, 68, RULE_name_identifier_list);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 309;
			name_identifier();
			State = 319;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==COMMA) {
				{
				{
				State = 310;
				Match(COMMA);
				State = 312;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				do {
					{
					{
					State = 311;
					Match(SP);
					}
					}
					State = 314;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				} while ( _la==SP );
				State = 316;
				name_identifier();
				}
				}
				State = 321;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class IndentContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode INDENT() { return GetToken(MajaParser.INDENT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] SP() { return GetTokens(MajaParser.SP); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SP(int i) {
			return GetToken(MajaParser.SP, i);
		}
		public IndentContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_indent; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMajaParserVisitor<TResult> typedVisitor = visitor as IMajaParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitIndent(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public IndentContext indent() {
		IndentContext _localctx = new IndentContext(Context, State);
		EnterRule(_localctx, 70, RULE_indent);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 322;
			Match(INDENT);
			State = 324;
			ErrorHandler.Sync(this);
			_alt = 1;
			do {
				switch (_alt) {
				case 1:
					{
					{
					State = 323;
					Match(SP);
					}
					}
					break;
				default:
					throw new NoViableAltException(this);
				}
				State = 326;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,32,Context);
			} while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER );
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class DedentContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DEDENT() { return GetToken(MajaParser.DEDENT, 0); }
		public DedentContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_dedent; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMajaParserVisitor<TResult> typedVisitor = visitor as IMajaParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitDedent(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public DedentContext dedent() {
		DedentContext _localctx = new DedentContext(Context, State);
		EnterRule(_localctx, 72, RULE_dedent);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 328;
			Match(DEDENT);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class NewlineContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode EOL() { return GetToken(MajaParser.EOL, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] SP() { return GetTokens(MajaParser.SP); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SP(int i) {
			return GetToken(MajaParser.SP, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COMMENT() { return GetToken(MajaParser.COMMENT, 0); }
		public NewlineContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_newline; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMajaParserVisitor<TResult> typedVisitor = visitor as IMajaParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNewline(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public NewlineContext newline() {
		NewlineContext _localctx = new NewlineContext(Context, State);
		EnterRule(_localctx, 74, RULE_newline);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 333;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==SP) {
				{
				{
				State = 330;
				Match(SP);
				}
				}
				State = 335;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 337;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==COMMENT) {
				{
				State = 336;
				Match(COMMENT);
				}
			}

			State = 339;
			Match(EOL);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x3', '\x18', '\x158', '\x4', '\x2', '\t', '\x2', '\x4', '\x3', 
		'\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', '\x5', '\x4', 
		'\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', '\t', '\b', 
		'\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', '\t', '\v', 
		'\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', '\t', 
		'\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x4', '\x14', '\t', '\x14', '\x4', '\x15', '\t', '\x15', '\x4', 
		'\x16', '\t', '\x16', '\x4', '\x17', '\t', '\x17', '\x4', '\x18', '\t', 
		'\x18', '\x4', '\x19', '\t', '\x19', '\x4', '\x1A', '\t', '\x1A', '\x4', 
		'\x1B', '\t', '\x1B', '\x4', '\x1C', '\t', '\x1C', '\x4', '\x1D', '\t', 
		'\x1D', '\x4', '\x1E', '\t', '\x1E', '\x4', '\x1F', '\t', '\x1F', '\x4', 
		' ', '\t', ' ', '\x4', '!', '\t', '!', '\x4', '\"', '\t', '\"', '\x4', 
		'#', '\t', '#', '\x4', '$', '\t', '$', '\x4', '%', '\t', '%', '\x4', '&', 
		'\t', '&', '\x4', '\'', '\t', '\'', '\x3', '\x2', '\x3', '\x2', '\x3', 
		'\x2', '\x3', '\x2', '\a', '\x2', 'S', '\n', '\x2', '\f', '\x2', '\xE', 
		'\x2', 'V', '\v', '\x2', '\x3', '\x2', '\x3', '\x2', '\a', '\x2', 'Z', 
		'\n', '\x2', '\f', '\x2', '\xE', '\x2', ']', '\v', '\x2', '\x3', '\x3', 
		'\x3', '\x3', '\x6', '\x3', '\x61', '\n', '\x3', '\r', '\x3', '\xE', '\x3', 
		'\x62', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x4', '\x3', 
		'\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', 
		'\x4', '\x3', '\x5', '\x3', '\x5', '\x6', '\x5', 'q', '\n', '\x5', '\r', 
		'\x5', '\xE', '\x5', 'r', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', 
		'\x6', '\x3', '\x6', '\x3', '\x6', '\x6', '\x6', '{', '\n', '\x6', '\r', 
		'\x6', '\xE', '\x6', '|', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x5', 
		'\a', '\x82', '\n', '\a', '\x3', '\b', '\x3', '\b', '\x3', '\t', '\x3', 
		'\t', '\x3', '\n', '\x3', '\n', '\x3', '\v', '\x3', '\v', '\x3', '\v', 
		'\x3', '\v', '\x5', '\v', '\x8E', '\n', '\v', '\x3', '\v', '\x3', '\v', 
		'\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\f', '\x3', 
		'\f', '\x3', '\f', '\x3', '\f', '\x3', '\r', '\x3', '\r', '\x3', '\r', 
		'\x3', '\r', '\x3', '\r', '\x3', '\r', '\a', '\r', '\xA0', '\n', '\r', 
		'\f', '\r', '\xE', '\r', '\xA3', '\v', '\r', '\x5', '\r', '\xA5', '\n', 
		'\r', '\x3', '\r', '\x3', '\r', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', 
		'\x3', '\xE', '\x3', '\xE', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', 
		'\x3', '\xF', '\x3', '\xF', '\x3', '\x10', '\x3', '\x10', '\x5', '\x10', 
		'\xB5', '\n', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x5', 
		'\x10', '\xBA', '\n', '\x10', '\x3', '\x10', '\x5', '\x10', '\xBD', '\n', 
		'\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', 
		'\x10', '\x5', '\x10', '\xC4', '\n', '\x10', '\x3', '\x11', '\x3', '\x11', 
		'\x3', '\x11', '\x5', '\x11', '\xC9', '\n', '\x11', '\x3', '\x11', '\x3', 
		'\x11', '\x6', '\x11', '\xCD', '\n', '\x11', '\r', '\x11', '\xE', '\x11', 
		'\xCE', '\x3', '\x12', '\x3', '\x12', '\x5', '\x12', '\xD3', '\n', '\x12', 
		'\x3', '\x13', '\x3', '\x13', '\x3', '\x13', '\x3', '\x13', '\x3', '\x13', 
		'\a', '\x13', '\xDA', '\n', '\x13', '\f', '\x13', '\xE', '\x13', '\xDD', 
		'\v', '\x13', '\x3', '\x13', '\x3', '\x13', '\x3', '\x14', '\x3', '\x14', 
		'\x3', '\x14', '\x5', '\x14', '\xE4', '\n', '\x14', '\x3', '\x15', '\x3', 
		'\x15', '\x3', '\x16', '\x3', '\x16', '\x3', '\x16', '\x3', '\x17', '\x3', 
		'\x17', '\x3', '\x18', '\x3', '\x18', '\x3', '\x18', '\x3', '\x18', '\x3', 
		'\x18', '\a', '\x18', '\xF2', '\n', '\x18', '\f', '\x18', '\xE', '\x18', 
		'\xF5', '\v', '\x18', '\x3', '\x18', '\x3', '\x18', '\x3', '\x19', '\x3', 
		'\x19', '\x5', '\x19', '\xFB', '\n', '\x19', '\x3', '\x1A', '\x3', '\x1A', 
		'\x3', '\x1A', '\x3', '\x1A', '\x3', '\x1A', '\x5', '\x1A', '\x102', '\n', 
		'\x1A', '\x3', '\x1B', '\x3', '\x1B', '\x3', '\x1B', '\x3', '\x1B', '\x3', 
		'\x1B', '\x3', '\x1C', '\x3', '\x1C', '\x3', '\x1C', '\x3', '\x1C', '\x3', 
		'\x1C', '\x3', '\x1D', '\x3', '\x1D', '\x5', '\x1D', '\x110', '\n', '\x1D', 
		'\x3', '\x1D', '\x3', '\x1D', '\x3', '\x1D', '\x5', '\x1D', '\x115', '\n', 
		'\x1D', '\x3', '\x1D', '\x3', '\x1D', '\x5', '\x1D', '\x119', '\n', '\x1D', 
		'\x3', '\x1E', '\x3', '\x1E', '\x3', '\x1F', '\x3', '\x1F', '\x3', ' ', 
		'\x3', ' ', '\x3', '!', '\x3', '!', '\x3', '!', '\a', '!', '\x124', '\n', 
		'!', '\f', '!', '\xE', '!', '\x127', '\v', '!', '\x3', '\"', '\x3', '\"', 
		'\x3', '\"', '\x6', '\"', '\x12C', '\n', '\"', '\r', '\"', '\xE', '\"', 
		'\x12D', '\x3', '\"', '\a', '\"', '\x131', '\n', '\"', '\f', '\"', '\xE', 
		'\"', '\x134', '\v', '\"', '\x3', '#', '\x3', '#', '\x3', '$', '\x3', 
		'$', '\x3', '$', '\x6', '$', '\x13B', '\n', '$', '\r', '$', '\xE', '$', 
		'\x13C', '\x3', '$', '\a', '$', '\x140', '\n', '$', '\f', '$', '\xE', 
		'$', '\x143', '\v', '$', '\x3', '%', '\x3', '%', '\x6', '%', '\x147', 
		'\n', '%', '\r', '%', '\xE', '%', '\x148', '\x3', '&', '\x3', '&', '\x3', 
		'\'', '\a', '\'', '\x14E', '\n', '\'', '\f', '\'', '\xE', '\'', '\x151', 
		'\v', '\'', '\x3', '\'', '\x5', '\'', '\x154', '\n', '\'', '\x3', '\'', 
		'\x3', '\'', '\x3', '\'', '\x2', '\x2', '(', '\x2', '\x4', '\x6', '\b', 
		'\n', '\f', '\xE', '\x10', '\x12', '\x14', '\x16', '\x18', '\x1A', '\x1C', 
		'\x1E', ' ', '\"', '$', '&', '(', '*', ',', '.', '\x30', '\x32', '\x34', 
		'\x36', '\x38', ':', '<', '>', '@', '\x42', '\x44', '\x46', 'H', 'J', 
		'L', '\x2', '\x2', '\x2', '\x15B', '\x2', 'T', '\x3', '\x2', '\x2', '\x2', 
		'\x4', '^', '\x3', '\x2', '\x2', '\x2', '\x6', 'g', '\x3', '\x2', '\x2', 
		'\x2', '\b', 'n', '\x3', '\x2', '\x2', '\x2', '\n', 'z', '\x3', '\x2', 
		'\x2', '\x2', '\f', '\x81', '\x3', '\x2', '\x2', '\x2', '\xE', '\x83', 
		'\x3', '\x2', '\x2', '\x2', '\x10', '\x85', '\x3', '\x2', '\x2', '\x2', 
		'\x12', '\x87', '\x3', '\x2', '\x2', '\x2', '\x14', '\x89', '\x3', '\x2', 
		'\x2', '\x2', '\x16', '\x95', '\x3', '\x2', '\x2', '\x2', '\x18', '\x99', 
		'\x3', '\x2', '\x2', '\x2', '\x1A', '\xA8', '\x3', '\x2', '\x2', '\x2', 
		'\x1C', '\xAD', '\x3', '\x2', '\x2', '\x2', '\x1E', '\xB2', '\x3', '\x2', 
		'\x2', '\x2', ' ', '\xCC', '\x3', '\x2', '\x2', '\x2', '\"', '\xD0', '\x3', 
		'\x2', '\x2', '\x2', '$', '\xD4', '\x3', '\x2', '\x2', '\x2', '&', '\xE3', 
		'\x3', '\x2', '\x2', '\x2', '(', '\xE5', '\x3', '\x2', '\x2', '\x2', '*', 
		'\xE7', '\x3', '\x2', '\x2', '\x2', ',', '\xEA', '\x3', '\x2', '\x2', 
		'\x2', '.', '\xEC', '\x3', '\x2', '\x2', '\x2', '\x30', '\xFA', '\x3', 
		'\x2', '\x2', '\x2', '\x32', '\xFC', '\x3', '\x2', '\x2', '\x2', '\x34', 
		'\x103', '\x3', '\x2', '\x2', '\x2', '\x36', '\x108', '\x3', '\x2', '\x2', 
		'\x2', '\x38', '\x10D', '\x3', '\x2', '\x2', '\x2', ':', '\x11A', '\x3', 
		'\x2', '\x2', '\x2', '<', '\x11C', '\x3', '\x2', '\x2', '\x2', '>', '\x11E', 
		'\x3', '\x2', '\x2', '\x2', '@', '\x120', '\x3', '\x2', '\x2', '\x2', 
		'\x42', '\x128', '\x3', '\x2', '\x2', '\x2', '\x44', '\x135', '\x3', '\x2', 
		'\x2', '\x2', '\x46', '\x137', '\x3', '\x2', '\x2', '\x2', 'H', '\x144', 
		'\x3', '\x2', '\x2', '\x2', 'J', '\x14A', '\x3', '\x2', '\x2', '\x2', 
		'L', '\x14F', '\x3', '\x2', '\x2', '\x2', 'N', 'S', '\x5', '\b', '\x5', 
		'\x2', 'O', 'S', '\x5', '\x4', '\x3', '\x2', 'P', 'S', '\x5', '\x6', '\x4', 
		'\x2', 'Q', 'S', '\x5', 'L', '\'', '\x2', 'R', 'N', '\x3', '\x2', '\x2', 
		'\x2', 'R', 'O', '\x3', '\x2', '\x2', '\x2', 'R', 'P', '\x3', '\x2', '\x2', 
		'\x2', 'R', 'Q', '\x3', '\x2', '\x2', '\x2', 'S', 'V', '\x3', '\x2', '\x2', 
		'\x2', 'T', 'R', '\x3', '\x2', '\x2', '\x2', 'T', 'U', '\x3', '\x2', '\x2', 
		'\x2', 'U', '[', '\x3', '\x2', '\x2', '\x2', 'V', 'T', '\x3', '\x2', '\x2', 
		'\x2', 'W', 'Z', '\x5', '\f', '\a', '\x2', 'X', 'Z', '\x5', 'L', '\'', 
		'\x2', 'Y', 'W', '\x3', '\x2', '\x2', '\x2', 'Y', 'X', '\x3', '\x2', '\x2', 
		'\x2', 'Z', ']', '\x3', '\x2', '\x2', '\x2', '[', 'Y', '\x3', '\x2', '\x2', 
		'\x2', '[', '\\', '\x3', '\x2', '\x2', '\x2', '\\', '\x3', '\x3', '\x2', 
		'\x2', '\x2', ']', '[', '\x3', '\x2', '\x2', '\x2', '^', '`', '\a', '\t', 
		'\x2', '\x2', '_', '\x61', '\a', '\x17', '\x2', '\x2', '`', '_', '\x3', 
		'\x2', '\x2', '\x2', '\x61', '\x62', '\x3', '\x2', '\x2', '\x2', '\x62', 
		'`', '\x3', '\x2', '\x2', '\x2', '\x62', '\x63', '\x3', '\x2', '\x2', 
		'\x2', '\x63', '\x64', '\x3', '\x2', '\x2', '\x2', '\x64', '\x65', '\x5', 
		'\x42', '\"', '\x2', '\x65', '\x66', '\x5', 'L', '\'', '\x2', '\x66', 
		'\x5', '\x3', '\x2', '\x2', '\x2', 'g', 'h', '\a', '\t', '\x2', '\x2', 
		'h', 'i', '\x5', 'L', '\'', '\x2', 'i', 'j', '\x5', 'H', '%', '\x2', 'j', 
		'k', '\x5', '\x42', '\"', '\x2', 'k', 'l', '\x5', 'L', '\'', '\x2', 'l', 
		'm', '\x5', 'J', '&', '\x2', 'm', '\a', '\x3', '\x2', '\x2', '\x2', 'n', 
		'p', '\a', '\n', '\x2', '\x2', 'o', 'q', '\a', '\x17', '\x2', '\x2', 'p', 
		'o', '\x3', '\x2', '\x2', '\x2', 'q', 'r', '\x3', '\x2', '\x2', '\x2', 
		'r', 'p', '\x3', '\x2', '\x2', '\x2', 'r', 's', '\x3', '\x2', '\x2', '\x2', 
		's', 't', '\x3', '\x2', '\x2', '\x2', 't', 'u', '\x5', '@', '!', '\x2', 
		'u', 'v', '\x5', 'L', '\'', '\x2', 'v', '\t', '\x3', '\x2', '\x2', '\x2', 
		'w', '{', '\x5', '\xE', '\b', '\x2', 'x', '{', '\x5', '\f', '\a', '\x2', 
		'y', '{', '\x5', 'L', '\'', '\x2', 'z', 'w', '\x3', '\x2', '\x2', '\x2', 
		'z', 'x', '\x3', '\x2', '\x2', '\x2', 'z', 'y', '\x3', '\x2', '\x2', '\x2', 
		'{', '|', '\x3', '\x2', '\x2', '\x2', '|', 'z', '\x3', '\x2', '\x2', '\x2', 
		'|', '}', '\x3', '\x2', '\x2', '\x2', '}', '\v', '\x3', '\x2', '\x2', 
		'\x2', '~', '\x82', '\x5', '\x14', '\v', '\x2', '\x7F', '\x82', '\x5', 
		'\x1E', '\x10', '\x2', '\x80', '\x82', '\x5', '\x38', '\x1D', '\x2', '\x81', 
		'~', '\x3', '\x2', '\x2', '\x2', '\x81', '\x7F', '\x3', '\x2', '\x2', 
		'\x2', '\x81', '\x80', '\x3', '\x2', '\x2', '\x2', '\x82', '\r', '\x3', 
		'\x2', '\x2', '\x2', '\x83', '\x84', '\x5', '\x10', '\t', '\x2', '\x84', 
		'\xF', '\x3', '\x2', '\x2', '\x2', '\x85', '\x86', '\x5', '\x12', '\n', 
		'\x2', '\x86', '\x11', '\x3', '\x2', '\x2', '\x2', '\x87', '\x88', '\a', 
		'\b', '\x2', '\x2', '\x88', '\x13', '\x3', '\x2', '\x2', '\x2', '\x89', 
		'\x8A', '\x5', '\x44', '#', '\x2', '\x8A', '\x8B', '\a', '\x12', '\x2', 
		'\x2', '\x8B', '\x8D', '\a', '\x17', '\x2', '\x2', '\x8C', '\x8E', '\x5', 
		'$', '\x13', '\x2', '\x8D', '\x8C', '\x3', '\x2', '\x2', '\x2', '\x8D', 
		'\x8E', '\x3', '\x2', '\x2', '\x2', '\x8E', '\x8F', '\x3', '\x2', '\x2', 
		'\x2', '\x8F', '\x90', '\x5', '\x18', '\r', '\x2', '\x90', '\x91', '\x5', 
		'L', '\'', '\x2', '\x91', '\x92', '\x5', 'H', '%', '\x2', '\x92', '\x93', 
		'\x5', '\n', '\x6', '\x2', '\x93', '\x94', '\x5', 'J', '&', '\x2', '\x94', 
		'\x15', '\x3', '\x2', '\x2', '\x2', '\x95', '\x96', '\x5', 'H', '%', '\x2', 
		'\x96', '\x97', '\x5', '\x14', '\v', '\x2', '\x97', '\x98', '\x5', 'J', 
		'&', '\x2', '\x98', '\x17', '\x3', '\x2', '\x2', '\x2', '\x99', '\xA4', 
		'\a', '\r', '\x2', '\x2', '\x9A', '\xA5', '\x5', '\x1A', '\xE', '\x2', 
		'\x9B', '\xA1', '\x5', '\x1C', '\xF', '\x2', '\x9C', '\x9D', '\a', '\x16', 
		'\x2', '\x2', '\x9D', '\x9E', '\a', '\x17', '\x2', '\x2', '\x9E', '\xA0', 
		'\x5', '\x1A', '\xE', '\x2', '\x9F', '\x9C', '\x3', '\x2', '\x2', '\x2', 
		'\xA0', '\xA3', '\x3', '\x2', '\x2', '\x2', '\xA1', '\x9F', '\x3', '\x2', 
		'\x2', '\x2', '\xA1', '\xA2', '\x3', '\x2', '\x2', '\x2', '\xA2', '\xA5', 
		'\x3', '\x2', '\x2', '\x2', '\xA3', '\xA1', '\x3', '\x2', '\x2', '\x2', 
		'\xA4', '\x9A', '\x3', '\x2', '\x2', '\x2', '\xA4', '\x9B', '\x3', '\x2', 
		'\x2', '\x2', '\xA4', '\xA5', '\x3', '\x2', '\x2', '\x2', '\xA5', '\xA6', 
		'\x3', '\x2', '\x2', '\x2', '\xA6', '\xA7', '\a', '\xE', '\x2', '\x2', 
		'\xA7', '\x19', '\x3', '\x2', '\x2', '\x2', '\xA8', '\xA9', '\x5', '\x44', 
		'#', '\x2', '\xA9', '\xAA', '\a', '\x12', '\x2', '\x2', '\xAA', '\xAB', 
		'\a', '\x17', '\x2', '\x2', '\xAB', '\xAC', '\x5', '\"', '\x12', '\x2', 
		'\xAC', '\x1B', '\x3', '\x2', '\x2', '\x2', '\xAD', '\xAE', '\a', '\v', 
		'\x2', '\x2', '\xAE', '\xAF', '\a', '\x12', '\x2', '\x2', '\xAF', '\xB0', 
		'\a', '\x17', '\x2', '\x2', '\xB0', '\xB1', '\x5', '\"', '\x12', '\x2', 
		'\xB1', '\x1D', '\x3', '\x2', '\x2', '\x2', '\xB2', '\xB4', '\x5', '\x44', 
		'#', '\x2', '\xB3', '\xB5', '\x5', '$', '\x13', '\x2', '\xB4', '\xB3', 
		'\x3', '\x2', '\x2', '\x2', '\xB4', '\xB5', '\x3', '\x2', '\x2', '\x2', 
		'\xB5', '\xB9', '\x3', '\x2', '\x2', '\x2', '\xB6', '\xB7', '\a', '\x12', 
		'\x2', '\x2', '\xB7', '\xB8', '\a', '\x17', '\x2', '\x2', '\xB8', '\xBA', 
		'\x5', '\"', '\x12', '\x2', '\xB9', '\xB6', '\x3', '\x2', '\x2', '\x2', 
		'\xB9', '\xBA', '\x3', '\x2', '\x2', '\x2', '\xBA', '\xBC', '\x3', '\x2', 
		'\x2', '\x2', '\xBB', '\xBD', '\a', '\x15', '\x2', '\x2', '\xBC', '\xBB', 
		'\x3', '\x2', '\x2', '\x2', '\xBC', '\xBD', '\x3', '\x2', '\x2', '\x2', 
		'\xBD', '\xBE', '\x3', '\x2', '\x2', '\x2', '\xBE', '\xC3', '\x5', 'L', 
		'\'', '\x2', '\xBF', '\xC0', '\x5', 'H', '%', '\x2', '\xC0', '\xC1', '\x5', 
		' ', '\x11', '\x2', '\xC1', '\xC2', '\x5', 'J', '&', '\x2', '\xC2', '\xC4', 
		'\x3', '\x2', '\x2', '\x2', '\xC3', '\xBF', '\x3', '\x2', '\x2', '\x2', 
		'\xC3', '\xC4', '\x3', '\x2', '\x2', '\x2', '\xC4', '\x1F', '\x3', '\x2', 
		'\x2', '\x2', '\xC5', '\xC9', '\x5', '\x32', '\x1A', '\x2', '\xC6', '\xC9', 
		'\x5', '\x34', '\x1B', '\x2', '\xC7', '\xC9', '\x5', '\x36', '\x1C', '\x2', 
		'\xC8', '\xC5', '\x3', '\x2', '\x2', '\x2', '\xC8', '\xC6', '\x3', '\x2', 
		'\x2', '\x2', '\xC8', '\xC7', '\x3', '\x2', '\x2', '\x2', '\xC9', '\xCA', 
		'\x3', '\x2', '\x2', '\x2', '\xCA', '\xCB', '\x5', 'L', '\'', '\x2', '\xCB', 
		'\xCD', '\x3', '\x2', '\x2', '\x2', '\xCC', '\xC8', '\x3', '\x2', '\x2', 
		'\x2', '\xCD', '\xCE', '\x3', '\x2', '\x2', '\x2', '\xCE', '\xCC', '\x3', 
		'\x2', '\x2', '\x2', '\xCE', '\xCF', '\x3', '\x2', '\x2', '\x2', '\xCF', 
		'!', '\x3', '\x2', '\x2', '\x2', '\xD0', '\xD2', '\x5', '\x44', '#', '\x2', 
		'\xD1', '\xD3', '\x5', '.', '\x18', '\x2', '\xD2', '\xD1', '\x3', '\x2', 
		'\x2', '\x2', '\xD2', '\xD3', '\x3', '\x2', '\x2', '\x2', '\xD3', '#', 
		'\x3', '\x2', '\x2', '\x2', '\xD4', '\xD5', '\a', '\xF', '\x2', '\x2', 
		'\xD5', '\xDB', '\x5', '&', '\x14', '\x2', '\xD6', '\xD7', '\a', '\x16', 
		'\x2', '\x2', '\xD7', '\xD8', '\a', '\x17', '\x2', '\x2', '\xD8', '\xDA', 
		'\x5', '&', '\x14', '\x2', '\xD9', '\xD6', '\x3', '\x2', '\x2', '\x2', 
		'\xDA', '\xDD', '\x3', '\x2', '\x2', '\x2', '\xDB', '\xD9', '\x3', '\x2', 
		'\x2', '\x2', '\xDB', '\xDC', '\x3', '\x2', '\x2', '\x2', '\xDC', '\xDE', 
		'\x3', '\x2', '\x2', '\x2', '\xDD', '\xDB', '\x3', '\x2', '\x2', '\x2', 
		'\xDE', '\xDF', '\a', '\x10', '\x2', '\x2', '\xDF', '%', '\x3', '\x2', 
		'\x2', '\x2', '\xE0', '\xE4', '\x5', '(', '\x15', '\x2', '\xE1', '\xE4', 
		'\x5', '*', '\x16', '\x2', '\xE2', '\xE4', '\x5', ',', '\x17', '\x2', 
		'\xE3', '\xE0', '\x3', '\x2', '\x2', '\x2', '\xE3', '\xE1', '\x3', '\x2', 
		'\x2', '\x2', '\xE3', '\xE2', '\x3', '\x2', '\x2', '\x2', '\xE4', '\'', 
		'\x3', '\x2', '\x2', '\x2', '\xE5', '\xE6', '\x5', '\x44', '#', '\x2', 
		'\xE6', ')', '\x3', '\x2', '\x2', '\x2', '\xE7', '\xE8', '\a', '\x11', 
		'\x2', '\x2', '\xE8', '\xE9', '\x5', '\x44', '#', '\x2', '\xE9', '+', 
		'\x3', '\x2', '\x2', '\x2', '\xEA', '\xEB', '\x5', ':', '\x1E', '\x2', 
		'\xEB', '-', '\x3', '\x2', '\x2', '\x2', '\xEC', '\xED', '\a', '\xF', 
		'\x2', '\x2', '\xED', '\xF3', '\x5', '\x30', '\x19', '\x2', '\xEE', '\xEF', 
		'\a', '\x16', '\x2', '\x2', '\xEF', '\xF0', '\a', '\x17', '\x2', '\x2', 
		'\xF0', '\xF2', '\x5', '\x30', '\x19', '\x2', '\xF1', '\xEE', '\x3', '\x2', 
		'\x2', '\x2', '\xF2', '\xF5', '\x3', '\x2', '\x2', '\x2', '\xF3', '\xF1', 
		'\x3', '\x2', '\x2', '\x2', '\xF3', '\xF4', '\x3', '\x2', '\x2', '\x2', 
		'\xF4', '\xF6', '\x3', '\x2', '\x2', '\x2', '\xF5', '\xF3', '\x3', '\x2', 
		'\x2', '\x2', '\xF6', '\xF7', '\a', '\x10', '\x2', '\x2', '\xF7', '/', 
		'\x3', '\x2', '\x2', '\x2', '\xF8', '\xFB', '\x5', '\x44', '#', '\x2', 
		'\xF9', '\xFB', '\x5', ':', '\x1E', '\x2', '\xFA', '\xF8', '\x3', '\x2', 
		'\x2', '\x2', '\xFA', '\xF9', '\x3', '\x2', '\x2', '\x2', '\xFB', '\x31', 
		'\x3', '\x2', '\x2', '\x2', '\xFC', '\x101', '\x5', '\x44', '#', '\x2', 
		'\xFD', '\xFE', '\a', '\x17', '\x2', '\x2', '\xFE', '\xFF', '\a', '\x14', 
		'\x2', '\x2', '\xFF', '\x100', '\a', '\x17', '\x2', '\x2', '\x100', '\x102', 
		'\x5', '<', '\x1F', '\x2', '\x101', '\xFD', '\x3', '\x2', '\x2', '\x2', 
		'\x101', '\x102', '\x3', '\x2', '\x2', '\x2', '\x102', '\x33', '\x3', 
		'\x2', '\x2', '\x2', '\x103', '\x104', '\x5', '\x44', '#', '\x2', '\x104', 
		'\x105', '\a', '\x12', '\x2', '\x2', '\x105', '\x106', '\a', '\x17', '\x2', 
		'\x2', '\x106', '\x107', '\x5', '\"', '\x12', '\x2', '\x107', '\x35', 
		'\x3', '\x2', '\x2', '\x2', '\x108', '\x109', '\a', '\x11', '\x2', '\x2', 
		'\x109', '\x10A', '\x5', '\x44', '#', '\x2', '\x10A', '\x10B', '\a', '\x17', 
		'\x2', '\x2', '\x10B', '\x10C', '\x5', '>', ' ', '\x2', '\x10C', '\x37', 
		'\x3', '\x2', '\x2', '\x2', '\x10D', '\x10F', '\x5', '\x44', '#', '\x2', 
		'\x10E', '\x110', '\a', '\x17', '\x2', '\x2', '\x10F', '\x10E', '\x3', 
		'\x2', '\x2', '\x2', '\x10F', '\x110', '\x3', '\x2', '\x2', '\x2', '\x110', 
		'\x111', '\x3', '\x2', '\x2', '\x2', '\x111', '\x114', '\a', '\x12', '\x2', 
		'\x2', '\x112', '\x113', '\a', '\x17', '\x2', '\x2', '\x113', '\x115', 
		'\x5', '\"', '\x12', '\x2', '\x114', '\x112', '\x3', '\x2', '\x2', '\x2', 
		'\x114', '\x115', '\x3', '\x2', '\x2', '\x2', '\x115', '\x118', '\x3', 
		'\x2', '\x2', '\x2', '\x116', '\x117', '\a', '\x14', '\x2', '\x2', '\x117', 
		'\x119', '\x5', ':', '\x1E', '\x2', '\x118', '\x116', '\x3', '\x2', '\x2', 
		'\x2', '\x118', '\x119', '\x3', '\x2', '\x2', '\x2', '\x119', '\x39', 
		'\x3', '\x2', '\x2', '\x2', '\x11A', '\x11B', '\x5', '<', '\x1F', '\x2', 
		'\x11B', ';', '\x3', '\x2', '\x2', '\x2', '\x11C', '\x11D', '\x3', '\x2', 
		'\x2', '\x2', '\x11D', '=', '\x3', '\x2', '\x2', '\x2', '\x11E', '\x11F', 
		'\x3', '\x2', '\x2', '\x2', '\x11F', '?', '\x3', '\x2', '\x2', '\x2', 
		'\x120', '\x125', '\x5', '\x44', '#', '\x2', '\x121', '\x122', '\a', '\x13', 
		'\x2', '\x2', '\x122', '\x124', '\x5', '\x44', '#', '\x2', '\x123', '\x121', 
		'\x3', '\x2', '\x2', '\x2', '\x124', '\x127', '\x3', '\x2', '\x2', '\x2', 
		'\x125', '\x123', '\x3', '\x2', '\x2', '\x2', '\x125', '\x126', '\x3', 
		'\x2', '\x2', '\x2', '\x126', '\x41', '\x3', '\x2', '\x2', '\x2', '\x127', 
		'\x125', '\x3', '\x2', '\x2', '\x2', '\x128', '\x132', '\x5', '@', '!', 
		'\x2', '\x129', '\x12B', '\a', '\x16', '\x2', '\x2', '\x12A', '\x12C', 
		'\a', '\x17', '\x2', '\x2', '\x12B', '\x12A', '\x3', '\x2', '\x2', '\x2', 
		'\x12C', '\x12D', '\x3', '\x2', '\x2', '\x2', '\x12D', '\x12B', '\x3', 
		'\x2', '\x2', '\x2', '\x12D', '\x12E', '\x3', '\x2', '\x2', '\x2', '\x12E', 
		'\x12F', '\x3', '\x2', '\x2', '\x2', '\x12F', '\x131', '\x5', '@', '!', 
		'\x2', '\x130', '\x129', '\x3', '\x2', '\x2', '\x2', '\x131', '\x134', 
		'\x3', '\x2', '\x2', '\x2', '\x132', '\x130', '\x3', '\x2', '\x2', '\x2', 
		'\x132', '\x133', '\x3', '\x2', '\x2', '\x2', '\x133', '\x43', '\x3', 
		'\x2', '\x2', '\x2', '\x134', '\x132', '\x3', '\x2', '\x2', '\x2', '\x135', 
		'\x136', '\a', '\f', '\x2', '\x2', '\x136', '\x45', '\x3', '\x2', '\x2', 
		'\x2', '\x137', '\x141', '\x5', '\x44', '#', '\x2', '\x138', '\x13A', 
		'\a', '\x16', '\x2', '\x2', '\x139', '\x13B', '\a', '\x17', '\x2', '\x2', 
		'\x13A', '\x139', '\x3', '\x2', '\x2', '\x2', '\x13B', '\x13C', '\x3', 
		'\x2', '\x2', '\x2', '\x13C', '\x13A', '\x3', '\x2', '\x2', '\x2', '\x13C', 
		'\x13D', '\x3', '\x2', '\x2', '\x2', '\x13D', '\x13E', '\x3', '\x2', '\x2', 
		'\x2', '\x13E', '\x140', '\x5', '\x44', '#', '\x2', '\x13F', '\x138', 
		'\x3', '\x2', '\x2', '\x2', '\x140', '\x143', '\x3', '\x2', '\x2', '\x2', 
		'\x141', '\x13F', '\x3', '\x2', '\x2', '\x2', '\x141', '\x142', '\x3', 
		'\x2', '\x2', '\x2', '\x142', 'G', '\x3', '\x2', '\x2', '\x2', '\x143', 
		'\x141', '\x3', '\x2', '\x2', '\x2', '\x144', '\x146', '\a', '\x3', '\x2', 
		'\x2', '\x145', '\x147', '\a', '\x17', '\x2', '\x2', '\x146', '\x145', 
		'\x3', '\x2', '\x2', '\x2', '\x147', '\x148', '\x3', '\x2', '\x2', '\x2', 
		'\x148', '\x146', '\x3', '\x2', '\x2', '\x2', '\x148', '\x149', '\x3', 
		'\x2', '\x2', '\x2', '\x149', 'I', '\x3', '\x2', '\x2', '\x2', '\x14A', 
		'\x14B', '\a', '\x4', '\x2', '\x2', '\x14B', 'K', '\x3', '\x2', '\x2', 
		'\x2', '\x14C', '\x14E', '\a', '\x17', '\x2', '\x2', '\x14D', '\x14C', 
		'\x3', '\x2', '\x2', '\x2', '\x14E', '\x151', '\x3', '\x2', '\x2', '\x2', 
		'\x14F', '\x14D', '\x3', '\x2', '\x2', '\x2', '\x14F', '\x150', '\x3', 
		'\x2', '\x2', '\x2', '\x150', '\x153', '\x3', '\x2', '\x2', '\x2', '\x151', 
		'\x14F', '\x3', '\x2', '\x2', '\x2', '\x152', '\x154', '\a', '\a', '\x2', 
		'\x2', '\x153', '\x152', '\x3', '\x2', '\x2', '\x2', '\x153', '\x154', 
		'\x3', '\x2', '\x2', '\x2', '\x154', '\x155', '\x3', '\x2', '\x2', '\x2', 
		'\x155', '\x156', '\a', '\x18', '\x2', '\x2', '\x156', 'M', '\x3', '\x2', 
		'\x2', '\x2', '%', 'R', 'T', 'Y', '[', '\x62', 'r', 'z', '|', '\x81', 
		'\x8D', '\xA1', '\xA4', '\xB4', '\xB9', '\xBC', '\xC3', '\xC8', '\xCE', 
		'\xD2', '\xDB', '\xE3', '\xF3', '\xFA', '\x101', '\x10F', '\x114', '\x118', 
		'\x125', '\x12D', '\x132', '\x13C', '\x141', '\x148', '\x14F', '\x153',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
} // namespace Maja.Compiler.Parser
